mysql --local-infile=1 -u root -p
SET GLOBAL local_infile=1;

use DB1_PROYECTO2;

drop table if exists `db1_proyecto2`.`temporal`;
CREATE TABLE `db1_proyecto2`.`temporal` (
  `NOMBRE_ELECCION` VARCHAR(30) NULL,
  `AÑO_ELECCION` INT NULL,
  `PAIS` VARCHAR(45) NULL,
  `REGION` VARCHAR(25) NULL,
  `DEPTO` VARCHAR(55) NULL,
  `MUNICIPIO` VARCHAR(75) NULL,
  `PARTIDO` VARCHAR(45) NULL,
  `NOMBRE_PARTIDO` VARCHAR(75) NULL,
  `SEXO` VARCHAR(25) NULL,
  `RAZA` VARCHAR(25) NULL,
  `ANALFABETOS` INT NULL,
  `ALFABETOS` INT NULL,
  `PRIMARIA` INT NULL,
  `NIVEL_MEDIO` INT NULL,
  `UNIVERSITARIOS` INT NULL)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

LOAD DATA LOCAL INFILE 'D:\\vainas Cusos U\\2do semestre 2021\\bases\\lab\\ICE-Fuente.csv' 
INTO TABLE db1_proyecto2.temporal 
COLUMNS TERMINATED BY ';'
LINES TERMINATED BY '\r\n' 
IGNORE 1 ROWS
(NOMBRE_ELECCION,AÑO_ELECCION,PAIS,REGION,DEPTO,MUNICIPIO,PARTIDO,NOMBRE_PARTIDO,SEXO,RAZA,
ANALFABETOS,ALFABETOS,@dummy,@dummy,PRIMARIA,NIVEL_MEDIO,UNIVERSITARIOS);